version: '3.8'

services:
  app:
    build: .
    container_name: books-api
    depends_on:
      - db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_REDIS_HOST=${SPRING_REDIS_HOST}
      - SPRING_REDIS_PORT=${SPRING_REDIS_PORT}
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: codeelevate
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - ./src/main/resources/static/:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge